version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"   # Web UI
      - "7077:7077"   # Spark master port
    networks:
      - spark-net

  spark-worker-1:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - spark-net

  spark-worker-2:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    networks:
      - spark-net

  pyspark-client:
    image: jupyter/pyspark-notebook
    ports:
    - "8888:8888"
    - "4040:4040"
    environment:
    - SPARK_MASTER=spark://spark-master:7077
    volumes:
    - ./notebooks:/home/jovyan/work
    networks:
    - spark-net

networks:
  spark-net:
    driver: bridge
